module.exports = {
  apps: [
    {
      name: "andon-api",
      script: "./app.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "4G",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/api-error.log",
      out_file: "./logs/api-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "andon-estatus",
      script: "./clienteEstatus.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "300M",
      error_file: "./logs/estatus-error.log",
      out_file: "./logs/estatus-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "andon-produccion",
      script: "./clienteProduccion.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "4G",
      error_file: "./logs/produccion-error.log",
      out_file: "./logs/produccion-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
